// Auto-generated by tools/ml/train_codec_predictor.py
#pragma once
// Returns 0 for BCJ, 1 for KANZIEXE
#ifdef __cplusplus
extern "C" {
#endif
#include "exe_predict_feature_index.h"

// Minimal feature struct (only used fields)
typedef struct {
    double data_sz;
    double text_ratio;
    double ro_ratio;
    double data_ratio;
    double ro_entropy;
    double data_entropy;
    double zero_runs_32;
    double ff_calljmp_cnt;
    double jcc32_cnt;
    double branch_density_per_kb;
    double imm64_mov_cnt;
    double avg_rel32_abs;
} apultra_CodecFeat;

static inline int apultra_dt_core(const apultra_CodecFeat *m) {
  if (m->jcc32_cnt <= 2439.500000000) {
    if (m->jcc32_cnt <= 1700.000000000) {
      if (m->data_sz <= 60496.000000000) {
        if (m->jcc32_cnt <= 1353.000000000) {
          return 0;
        } else {
          if (m->data_ratio <= 0.042204501) {
            return 0;
          } else {
            return 0;
          }
        }
      } else {
        if (m->ro_ratio <= 0.310680509) {
          return 0;
        } else {
          return 1;
        }
      }
    } else {
      if (m->ro_entropy <= 5.119324684) {
        return 1;
      } else {
        if (m->ro_entropy <= 5.360195160) {
          return 0;
        } else {
          return 0;
        }
      }
    }
  } else {
    if (m->data_ratio <= 0.038079001) {
      if (m->zero_runs_32 <= 10.500000000) {
        if (m->data_entropy <= 2.164999008) {
          return 0;
        } else {
          if (m->imm64_mov_cnt <= 169.000000000) {
            return 1;
          } else {
            return 1;
          }
        }
      } else {
        if (m->data_entropy <= 2.476066589) {
          if (m->ro_ratio <= 0.322385505) {
            return 0;
          } else {
            return 0;
          }
        } else {
          if (m->ff_calljmp_cnt <= 5529.000000000) {
            return 1;
          } else {
            return 0;
          }
        }
      }
    } else {
      if (m->branch_density_per_kb <= 38.270549774) {
        if (m->branch_density_per_kb <= 28.322659492) {
          return 0;
        } else {
          if (m->avg_rel32_abs <= 158282280.000000000) {
            if (m->ro_ratio <= 0.467447996) {
              return 1;
            } else {
              return 1;
            }
          } else {
            return 1;
          }
        }
      } else {
        if (m->branch_density_per_kb <= 39.174299240) {
          return 0;
        } else {
          if (m->text_ratio <= 0.507631510) {
            return 1;
          } else {
            return 0;
          }
        }
      }
    }
  }
}

static inline int apultra_dt_predict_from_pvec(const double *in) {
    apultra_CodecFeat m; memset(&m, 0, sizeof(m));
    m.data_sz = in[PP_FEAT_data_sz];
    m.text_ratio = in[PP_FEAT_text_ratio];
    m.ro_ratio = in[PP_FEAT_ro_ratio];
    m.data_ratio = in[PP_FEAT_data_ratio];
    m.ro_entropy = in[PP_FEAT_ro_entropy];
    m.data_entropy = in[PP_FEAT_data_entropy];
    m.zero_runs_32 = in[PP_FEAT_zero_runs_32];
    m.ff_calljmp_cnt = in[PP_FEAT_ff_calljmp_cnt];
    m.jcc32_cnt = in[PP_FEAT_jcc32_cnt];
    m.branch_density_per_kb = in[PP_FEAT_branch_density_per_kb];
    m.imm64_mov_cnt = in[PP_FEAT_imm64_mov_cnt];
    m.avg_rel32_abs = in[PP_FEAT_avg_rel32_abs];
    return apultra_dt_core(&m);
}

#ifdef __cplusplus
}
#endif
