// Auto-generated by tools/ml/train_blz_predictor.py
#pragma once
// Returns 0 for BCJ, 1 for KANZIEXE
#ifdef __cplusplus
extern "C" {
#endif
#include "exe_predict_feature_index.h"

// Minimal feature struct (only used fields)
typedef struct {
    double ro_sz;
    double data_sz;
    double ro_ratio;
    double data_ratio;
    double text_entropy;
    double zero_runs_16;
    double ascii_ratio_rodata;
    double e8_cnt;
    double jcc32_cnt;
    double branch_density_per_kb;
    double riprel_estimate;
    double nop_ratio_text;
    double imm64_mov_cnt;
    double rel32_intext_cnt;
    double rel32_disp_entropy8;
} BlzFeat;

static inline int blz_dt_core(const BlzFeat *m) {
  if (m->jcc32_cnt <= 1759.500000000) {
    if (m->jcc32_cnt <= 1217.500000000) {
      if (m->ro_sz <= 217688.000000000) {
        if (m->jcc32_cnt <= 889.000000000) {
          return 0;
        } else {
          if (m->rel32_intext_cnt <= 1863.500000000) {
            return 0;
          } else {
            return 0;
          }
        }
      } else {
        return 0;
      }
    } else {
      if (m->riprel_estimate <= 924.500000000) {
        return 1;
      } else {
        if (m->data_sz <= 23800.000000000) {
          return 0;
        } else {
          return 0;
        }
      }
    }
  } else {
    if (m->data_ratio <= 0.039404999) {
      if (m->text_entropy <= 6.245585918) {
        if (m->jcc32_cnt <= 2001.500000000) {
          return 1;
        } else {
          if (m->jcc32_cnt <= 3169.500000000) {
            return 0;
          } else {
            if (m->branch_density_per_kb <= 36.240652084) {
              return 0;
            } else {
              return 1;
            }
          }
        }
      } else {
        if (m->imm64_mov_cnt <= 35.500000000) {
          return 0;
        } else {
          if (m->rel32_disp_entropy8 <= 2.217891932) {
            if (m->nop_ratio_text <= 0.002695500) {
              return 1;
            } else {
              if (m->riprel_estimate <= 2951.500000000) {
                return 1;
              } else {
                if (m->data_sz <= 29040.000000000) {
                  return 0;
                } else {
                  return 1;
                }
              }
            }
          } else {
            return 0;
          }
        }
      }
    } else {
      if (m->ascii_ratio_rodata <= 0.379543498) {
        if (m->ro_ratio <= 0.338155493) {
          return 1;
        } else {
          if (m->e8_cnt <= 21657.500000000) {
            return 1;
          } else {
            return 1;
          }
        }
      } else {
        if (m->zero_runs_16 <= 1631.500000000) {
          if (m->nop_ratio_text <= 0.002594000) {
            return 1;
          } else {
            if (m->zero_runs_16 <= 966.500000000) {
              return 1;
            } else {
              return 1;
            }
          }
        } else {
          return 0;
        }
      }
    }
  }
}

static inline int blz_dt_predict_from_pvec(const double *in) {
    BlzFeat m; memset(&m, 0, sizeof(m));
    m.ro_sz = in[PP_FEAT_ro_sz];
    m.data_sz = in[PP_FEAT_data_sz];
    m.ro_ratio = in[PP_FEAT_ro_ratio];
    m.data_ratio = in[PP_FEAT_data_ratio];
    m.text_entropy = in[PP_FEAT_text_entropy];
    m.zero_runs_16 = in[PP_FEAT_zero_runs_16];
    m.ascii_ratio_rodata = in[PP_FEAT_ascii_ratio_rodata];
    m.e8_cnt = in[PP_FEAT_e8_cnt];
    m.jcc32_cnt = in[PP_FEAT_jcc32_cnt];
    m.branch_density_per_kb = in[PP_FEAT_branch_density_per_kb];
    m.riprel_estimate = in[PP_FEAT_riprel_estimate];
    m.nop_ratio_text = in[PP_FEAT_nop_ratio_text];
    m.imm64_mov_cnt = in[PP_FEAT_imm64_mov_cnt];
    m.rel32_intext_cnt = in[PP_FEAT_rel32_intext_cnt];
    m.rel32_disp_entropy8 = in[PP_FEAT_rel32_disp_entropy8];
    return blz_dt_core(&m);
}

#ifdef __cplusplus
}
#endif
