// Auto-generated by tools/ml/train_codec_predictor.py
#pragma once
// Returns 0 for BCJ, 1 for KANZIEXE
#ifdef __cplusplus
extern "C" {
#endif
#include "exe_predict_feature_index.h"

// Minimal feature struct (only used fields)
typedef struct {
    double file_size;
    double text_sz;
    double ro_sz;
    double data_sz;
    double data_ratio;
    double data_entropy;
    double zeros_ratio_total;
    double align_pad_ratio;
    double bss_sz;
} csc_CodecFeat;

static inline int csc_dt_core(const csc_CodecFeat *m) {
  if (m->file_size <= 18636.000000000) {
    if (m->data_ratio <= 0.047684999) {
      if (m->text_sz <= 6517.000000000) {
        if (m->data_sz <= 676.000000000) {
          return 1;
        } else {
          return 1;
        }
      } else {
        return 0;
      }
    } else {
      if (m->zeros_ratio_total <= 0.535514504) {
        if (m->data_sz <= 848.000000000) {
          if (m->zeros_ratio_total <= 0.518362999) {
            return 0;
          } else {
            return 1;
          }
        } else {
          return 1;
        }
      } else {
        return 1;
      }
    }
  } else {
    if (m->data_entropy <= 5.965716362) {
      if (m->data_sz <= 884.000000000) {
        if (m->bss_sz <= 135.000000000) {
          return 1;
        } else {
          if (m->ro_sz <= 6314.000000000) {
            return 1;
          } else {
            return 1;
          }
        }
      } else {
        if (m->align_pad_ratio <= 0.101706501) {
          return 1;
        } else {
          return 1;
        }
      }
    } else {
      return 1;
    }
  }
}

static inline int csc_dt_predict_from_pvec(const double *in) {
    csc_CodecFeat m; memset(&m, 0, sizeof(m));
    m.file_size = in[PP_FEAT_file_size];
    m.text_sz = in[PP_FEAT_text_sz];
    m.ro_sz = in[PP_FEAT_ro_sz];
    m.data_sz = in[PP_FEAT_data_sz];
    m.data_ratio = in[PP_FEAT_data_ratio];
    m.data_entropy = in[PP_FEAT_data_entropy];
    m.zeros_ratio_total = in[PP_FEAT_zeros_ratio_total];
    m.align_pad_ratio = in[PP_FEAT_align_pad_ratio];
    m.bss_sz = in[PP_FEAT_bss_sz];
    return csc_dt_core(&m);
}

#ifdef __cplusplus
}
#endif
