// Auto-generated by tools/ml/train_codec_predictor.py
#pragma once
// Returns 0 for BCJ, 1 for KANZIEXE
#ifdef __cplusplus
extern "C" {
#endif
#include "exe_predict_feature_index.h"

// Minimal feature struct (only used fields)
typedef struct {
    double data_ratio;
    double text_entropy;
    double data_entropy;
    double zeros_ratio_total;
    double eb_cnt;
    double align_pad_ratio;
    double ro_ptr_like_cnt;
    double ret_cnt;
    double max_rel32_abs;
} density_CodecFeat;

static inline int density_dt_core(const density_CodecFeat *m) {
  if (m->zeros_ratio_total <= 0.113130499) {
    return 0;
  } else {
    if (m->ret_cnt <= 36.500000000) {
      if (m->ro_ptr_like_cnt <= 207.500000000) {
        if (m->zeros_ratio_total <= 0.423477501) {
          return 0;
        } else {
          return 0;
        }
      } else {
        return 0;
      }
    } else {
      if (m->align_pad_ratio <= 0.006956000) {
        if (m->text_entropy <= 6.276724577) {
          return 0;
        } else {
          return 0;
        }
      } else {
        if (m->text_entropy <= 5.947710037) {
          if (m->data_entropy <= 1.867497981) {
            return 0;
          } else {
            if (m->max_rel32_abs <= 2065432576.000000000) {
              return 0;
            } else {
              if (m->data_ratio <= 0.031459999) {
                return 0;
              } else {
                return 0;
              }
            }
          }
        } else {
          if (m->eb_cnt <= 23.000000000) {
            return 0;
          } else {
            return 0;
          }
        }
      }
    }
  }
}

static inline int density_dt_predict_from_pvec(const double *in) {
    density_CodecFeat m; memset(&m, 0, sizeof(m));
    m.data_ratio = in[PP_FEAT_data_ratio];
    m.text_entropy = in[PP_FEAT_text_entropy];
    m.data_entropy = in[PP_FEAT_data_entropy];
    m.zeros_ratio_total = in[PP_FEAT_zeros_ratio_total];
    m.eb_cnt = in[PP_FEAT_eb_cnt];
    m.align_pad_ratio = in[PP_FEAT_align_pad_ratio];
    m.ro_ptr_like_cnt = in[PP_FEAT_ro_ptr_like_cnt];
    m.ret_cnt = in[PP_FEAT_ret_cnt];
    m.max_rel32_abs = in[PP_FEAT_max_rel32_abs];
    return density_dt_core(&m);
}

#ifdef __cplusplus
}
#endif
