// Auto-generated by tools/ml/train_codec_predictor.py
#pragma once
// Returns 0 for BCJ, 1 for KANZIEXE
#ifdef __cplusplus
extern "C" {
#endif
#include "exe_predict_feature_index.h"

// Minimal feature struct (only used fields)
typedef struct {
    double file_size;
    double data_sz;
    double text_ratio;
    double data_ratio;
    double text_entropy;
    double data_entropy;
    double zeros_ratio_total;
    double ff_calljmp_cnt;
    double eb_cnt;
    double jcc32_cnt;
    double rel32_intext_ratio;
    double rel32_disp_entropy8;
    double bss_sz;
    double avg_rel32_abs;
} doboz_CodecFeat;

static inline int doboz_dt_core(const doboz_CodecFeat *m) {
  if (m->jcc32_cnt <= 1347.000000000) {
    if (m->file_size <= 365368.000000000) {
      if (m->jcc32_cnt <= 889.000000000) {
        if (m->data_entropy <= 2.820141912) {
          return 0;
        } else {
          if (m->jcc32_cnt <= 691.500000000) {
            return 0;
          } else {
            return 0;
          }
        }
      } else {
        if (m->ff_calljmp_cnt <= 306.000000000) {
          return 0;
        } else {
          if (m->zeros_ratio_total <= 0.235202998) {
            return 0;
          } else {
            return 0;
          }
        }
      }
    } else {
      if (m->zeros_ratio_total <= 0.242353998) {
        return 0;
      } else {
        return 1;
      }
    }
  } else {
    if (m->data_ratio <= 0.017827501) {
      if (m->text_entropy <= 6.226255417) {
        if (m->zeros_ratio_total <= 0.169087499) {
          return 0;
        } else {
          return 0;
        }
      } else {
        if (m->rel32_disp_entropy8 <= 2.168735981) {
          if (m->data_entropy <= 2.484653473) {
            return 1;
          } else {
            return 1;
          }
        } else {
          return 0;
        }
      }
    } else {
      if (m->jcc32_cnt <= 1577.500000000) {
        if (m->rel32_disp_entropy8 <= 1.674688995) {
          return 0;
        } else {
          return 1;
        }
      } else {
        if (m->eb_cnt <= 30290.500000000) {
          if (m->avg_rel32_abs <= 57443210.000000000) {
            return 0;
          } else {
            if (m->data_ratio <= 0.038114000) {
              if (m->bss_sz <= 29250.000000000) {
                if (m->text_ratio <= 0.628944010) {
                  if (m->data_sz <= 27352.000000000) {
                    return 1;
                  } else {
                    return 1;
                  }
                } else {
                  return 1;
                }
              } else {
                return 1;
              }
            } else {
              if (m->rel32_intext_ratio <= 0.824029505) {
                return 1;
              } else {
                return 1;
              }
            }
          }
        } else {
          return 0;
        }
      }
    }
  }
}

static inline int doboz_dt_predict_from_pvec(const double *in) {
    doboz_CodecFeat m; memset(&m, 0, sizeof(m));
    m.file_size = in[PP_FEAT_file_size];
    m.data_sz = in[PP_FEAT_data_sz];
    m.text_ratio = in[PP_FEAT_text_ratio];
    m.data_ratio = in[PP_FEAT_data_ratio];
    m.text_entropy = in[PP_FEAT_text_entropy];
    m.data_entropy = in[PP_FEAT_data_entropy];
    m.zeros_ratio_total = in[PP_FEAT_zeros_ratio_total];
    m.ff_calljmp_cnt = in[PP_FEAT_ff_calljmp_cnt];
    m.eb_cnt = in[PP_FEAT_eb_cnt];
    m.jcc32_cnt = in[PP_FEAT_jcc32_cnt];
    m.rel32_intext_ratio = in[PP_FEAT_rel32_intext_ratio];
    m.rel32_disp_entropy8 = in[PP_FEAT_rel32_disp_entropy8];
    m.bss_sz = in[PP_FEAT_bss_sz];
    m.avg_rel32_abs = in[PP_FEAT_avg_rel32_abs];
    return doboz_dt_core(&m);
}

#ifdef __cplusplus
}
#endif
