// Auto-generated by tools/ml/train_codec_predictor.py
#pragma once
// Returns 0 for BCJ, 1 for KANZIEXE
#ifdef __cplusplus
extern "C" {
#endif
#include "exe_predict_feature_index.h"

// Minimal feature struct (only used fields)
typedef struct {
    double text_sz;
    double ro_sz;
    double data_ratio;
    double zeros_ratio_total;
    double ascii_ratio_rodata;
    double e9_cnt;
    double jcc32_cnt;
    double branch_density_per_kb;
    double nop_ratio_text;
    double imm64_mov_cnt;
    double rel32_intext_ratio;
    double rel_branch_ratio;
    double max_rel32_abs;
} exo_CodecFeat;

static inline int exo_dt_core(const exo_CodecFeat *m) {
  if (m->jcc32_cnt <= 1752.500000000) {
    if (m->ro_sz <= 109522.000000000) {
      if (m->rel_branch_ratio <= 0.950499505) {
        if (m->jcc32_cnt <= 1373.500000000) {
          if (m->zeros_ratio_total <= 0.184083499) {
            if (m->zeros_ratio_total <= 0.176650502) {
              return 0;
            } else {
              return 0;
            }
          } else {
            if (m->ascii_ratio_rodata <= 0.571199507) {
              return 0;
            } else {
              if (m->max_rel32_abs <= 2118995520.000000000) {
                return 0;
              } else {
                return 0;
              }
            }
          }
        } else {
          return 0;
        }
      } else {
        return 0;
      }
    } else {
      if (m->data_ratio <= 0.074868001) {
        if (m->jcc32_cnt <= 1193.000000000) {
          return 0;
        } else {
          return 0;
        }
      } else {
        return 1;
      }
    }
  } else {
    if (m->branch_density_per_kb <= 28.747626305) {
      if (m->nop_ratio_text <= 0.002018500) {
        return 1;
      } else {
        if (m->text_sz <= 677068.000000000) {
          return 0;
        } else {
          return 0;
        }
      }
    } else {
      if (m->rel32_intext_ratio <= 0.950859487) {
        if (m->ascii_ratio_rodata <= 0.334237501) {
          return 0;
        } else {
          if (m->e9_cnt <= 1882.000000000) {
            if (m->ro_sz <= 73430.000000000) {
              return 1;
            } else {
              return 0;
            }
          } else {
            if (m->imm64_mov_cnt <= 176.000000000) {
              return 1;
            } else {
              return 1;
            }
          }
        }
      } else {
        return 0;
      }
    }
  }
}

static inline int exo_dt_predict_from_pvec(const double *in) {
    exo_CodecFeat m; memset(&m, 0, sizeof(m));
    m.text_sz = in[PP_FEAT_text_sz];
    m.ro_sz = in[PP_FEAT_ro_sz];
    m.data_ratio = in[PP_FEAT_data_ratio];
    m.zeros_ratio_total = in[PP_FEAT_zeros_ratio_total];
    m.ascii_ratio_rodata = in[PP_FEAT_ascii_ratio_rodata];
    m.e9_cnt = in[PP_FEAT_e9_cnt];
    m.jcc32_cnt = in[PP_FEAT_jcc32_cnt];
    m.branch_density_per_kb = in[PP_FEAT_branch_density_per_kb];
    m.nop_ratio_text = in[PP_FEAT_nop_ratio_text];
    m.imm64_mov_cnt = in[PP_FEAT_imm64_mov_cnt];
    m.rel32_intext_ratio = in[PP_FEAT_rel32_intext_ratio];
    m.rel_branch_ratio = in[PP_FEAT_rel_branch_ratio];
    m.max_rel32_abs = in[PP_FEAT_max_rel32_abs];
    return exo_dt_core(&m);
}

#ifdef __cplusplus
}
#endif
