// Auto-generated by tools/ml/train_codec_predictor.py
#pragma once
// Returns 0 for BCJ, 1 for KANZIEXE
#ifdef __cplusplus
extern "C" {
#endif
#include "exe_predict_feature_index.h"

// Minimal feature struct (only used fields)
typedef struct {
    double file_size;
    double ro_sz;
    double text_ratio;
    double data_ratio;
    double text_entropy;
    double data_entropy;
    double zeros_ratio_total;
    double ascii_ratio_rodata;
    double e9_cnt;
    double eb_cnt;
    double jcc32_cnt;
    double nop_ratio_text;
    double imm64_mov_cnt;
    double ro_ptr_like_cnt;
    double rel32_intext_cnt;
    double bss_sz;
    double ret_cnt;
    double rel_branch_ratio;
    double avg_rel32_abs;
} lz4_CodecFeat;

static inline int lz4_dt_core(const lz4_CodecFeat *m) {
  if (m->file_size <= 705308.000000000) {
    if (m->jcc32_cnt <= 1700.000000000) {
      if (m->rel_branch_ratio <= 0.950499505) {
        if (m->ro_sz <= 155670.000000000) {
          if (m->zeros_ratio_total <= 0.184083499) {
            if (m->zeros_ratio_total <= 0.177504502) {
              return 0;
            } else {
              return 0;
            }
          } else {
            if (m->ascii_ratio_rodata <= 0.571199507) {
              return 0;
            } else {
              if (m->e9_cnt <= 361.500000000) {
                return 0;
              } else {
                return 0;
              }
            }
          }
        } else {
          return 0;
        }
      } else {
        if (m->ret_cnt <= 661.000000000) {
          return 0;
        } else {
          return 0;
        }
      }
    } else {
      if (m->eb_cnt <= 452.500000000) {
        return 1;
      } else {
        if (m->jcc32_cnt <= 2439.500000000) {
          if (m->data_entropy <= 1.757790506) {
            return 0;
          } else {
            return 0;
          }
        } else {
          if (m->ro_ptr_like_cnt <= 1816.000000000) {
            if (m->text_ratio <= 0.658716977) {
              return 1;
            } else {
              return 0;
            }
          } else {
            return 0;
          }
        }
      }
    }
  } else {
    if (m->data_ratio <= 0.033034500) {
      if (m->rel_branch_ratio <= 0.911991984) {
        return 0;
      } else {
        if (m->imm64_mov_cnt <= 1030.500000000) {
          if (m->bss_sz <= 960.000000000) {
            return 0;
          } else {
            if (m->text_entropy <= 6.338900566) {
              return 1;
            } else {
              return 1;
            }
          }
        } else {
          return 0;
        }
      }
    } else {
      if (m->ret_cnt <= 22997.000000000) {
        if (m->file_size <= 827780.000000000) {
          return 1;
        } else {
          if (m->nop_ratio_text <= 0.003317500) {
            if (m->ro_ptr_like_cnt <= 5426.500000000) {
              return 1;
            } else {
              return 1;
            }
          } else {
            return 1;
          }
        }
      } else {
        if (m->rel32_intext_cnt <= 130434.000000000) {
          if (m->avg_rel32_abs <= 139686864.000000000) {
            return 0;
          } else {
            return 0;
          }
        } else {
          return 1;
        }
      }
    }
  }
}

static inline int lz4_dt_predict_from_pvec(const double *in) {
    lz4_CodecFeat m; memset(&m, 0, sizeof(m));
    m.file_size = in[PP_FEAT_file_size];
    m.ro_sz = in[PP_FEAT_ro_sz];
    m.text_ratio = in[PP_FEAT_text_ratio];
    m.data_ratio = in[PP_FEAT_data_ratio];
    m.text_entropy = in[PP_FEAT_text_entropy];
    m.data_entropy = in[PP_FEAT_data_entropy];
    m.zeros_ratio_total = in[PP_FEAT_zeros_ratio_total];
    m.ascii_ratio_rodata = in[PP_FEAT_ascii_ratio_rodata];
    m.e9_cnt = in[PP_FEAT_e9_cnt];
    m.eb_cnt = in[PP_FEAT_eb_cnt];
    m.jcc32_cnt = in[PP_FEAT_jcc32_cnt];
    m.nop_ratio_text = in[PP_FEAT_nop_ratio_text];
    m.imm64_mov_cnt = in[PP_FEAT_imm64_mov_cnt];
    m.ro_ptr_like_cnt = in[PP_FEAT_ro_ptr_like_cnt];
    m.rel32_intext_cnt = in[PP_FEAT_rel32_intext_cnt];
    m.bss_sz = in[PP_FEAT_bss_sz];
    m.ret_cnt = in[PP_FEAT_ret_cnt];
    m.rel_branch_ratio = in[PP_FEAT_rel_branch_ratio];
    m.avg_rel32_abs = in[PP_FEAT_avg_rel32_abs];
    return lz4_dt_core(&m);
}

#ifdef __cplusplus
}
#endif
