// Auto-generated by tools/ml/train_codec_predictor.py
#pragma once
// Returns 0 for BCJ, 1 for KANZIEXE
#ifdef __cplusplus
extern "C" {
#endif
#include "exe_predict_feature_index.h"

// Minimal feature struct (only used fields)
typedef struct {
    double etype;
    double ro_sz;
    double data_ratio;
    double zeros_ratio_total;
    double zero_runs_32;
    double eb_cnt;
    double jcc32_cnt;
    double branch_density_per_kb;
    double nop_ratio_text;
    double ro_ptr_like_cnt;
    double rel32_intext_ratio;
    double rel_branch_ratio;
} lzav_CodecFeat;

static inline int lzav_dt_core(const lzav_CodecFeat *m) {
  if (m->jcc32_cnt <= 1225.000000000) {
    if (m->ro_sz <= 223640.000000000) {
      if (m->jcc32_cnt <= 889.000000000) {
        return 0;
      } else {
        if (m->eb_cnt <= 211.500000000) {
          return 0;
        } else {
          return 0;
        }
      }
    } else {
      return 0;
    }
  } else {
    if (m->zeros_ratio_total <= 0.321059510) {
      if (m->nop_ratio_text <= 0.002705000) {
        if (m->zeros_ratio_total <= 0.214015998) {
          if (m->ro_ptr_like_cnt <= 612.000000000) {
            return 1;
          } else {
            if (m->nop_ratio_text <= 0.002435500) {
              if (m->data_ratio <= 0.022434001) {
                return 0;
              } else {
                if (m->rel_branch_ratio <= 0.932356507) {
                  return 0;
                } else {
                  return 1;
                }
              }
            } else {
              return 0;
            }
          }
        } else {
          if (m->zero_runs_32 <= 58.500000000) {
            if (m->rel32_intext_ratio <= 0.871429980) {
              if (m->ro_ptr_like_cnt <= 3928.000000000) {
                return 1;
              } else {
                return 1;
              }
            } else {
              if (m->nop_ratio_text <= 0.002379000) {
                return 1;
              } else {
                return 0;
              }
            }
          } else {
            return 0;
          }
        }
      } else {
        if (m->etype <= 2.500000000) {
          return 1;
        } else {
          if (m->eb_cnt <= 458.000000000) {
            return 0;
          } else {
            if (m->data_ratio <= 0.158110000) {
              if (m->nop_ratio_text <= 0.002735000) {
                return 0;
              } else {
                if (m->branch_density_per_kb <= 34.321161270) {
                  if (m->rel32_intext_ratio <= 0.873410493) {
                    return 0;
                  } else {
                    return 0;
                  }
                } else {
                  return 0;
                }
              }
            } else {
              return 0;
            }
          }
        }
      }
    } else {
      if (m->branch_density_per_kb <= 35.458044052) {
        return 1;
      } else {
        return 1;
      }
    }
  }
}

static inline int lzav_dt_predict_from_pvec(const double *in) {
    lzav_CodecFeat m; memset(&m, 0, sizeof(m));
    m.etype = in[PP_FEAT_etype];
    m.ro_sz = in[PP_FEAT_ro_sz];
    m.data_ratio = in[PP_FEAT_data_ratio];
    m.zeros_ratio_total = in[PP_FEAT_zeros_ratio_total];
    m.zero_runs_32 = in[PP_FEAT_zero_runs_32];
    m.eb_cnt = in[PP_FEAT_eb_cnt];
    m.jcc32_cnt = in[PP_FEAT_jcc32_cnt];
    m.branch_density_per_kb = in[PP_FEAT_branch_density_per_kb];
    m.nop_ratio_text = in[PP_FEAT_nop_ratio_text];
    m.ro_ptr_like_cnt = in[PP_FEAT_ro_ptr_like_cnt];
    m.rel32_intext_ratio = in[PP_FEAT_rel32_intext_ratio];
    m.rel_branch_ratio = in[PP_FEAT_rel_branch_ratio];
    return lzav_dt_core(&m);
}

#ifdef __cplusplus
}
#endif
