// Auto-generated by tools/ml/train_codec_predictor.py
#pragma once
// Returns 0 for BCJ, 1 for KANZIEXE
#ifdef __cplusplus
extern "C" {
#endif
#include "exe_predict_feature_index.h"

// Minimal feature struct (only used fields)
typedef struct {
    double file_size;
    double text_sz;
    double ro_sz;
    double data_ratio;
    double text_entropy;
    double data_entropy;
    double zeros_ratio_total;
    double ascii_ratio_rodata;
    double e8_cnt;
    double jcc32_cnt;
    double branch_density_per_kb;
    double riprel_estimate;
    double nop_ratio_text;
    double align_pad_ratio;
    double ro_ptr_like_cnt;
    double rel32_intext_cnt;
    double bss_sz;
    double ret_cnt;
    double rel_branch_ratio;
    double avg_rel32_abs;
    double max_rel32_abs;
} lzfse_CodecFeat;

static inline int lzfse_dt_core(const lzfse_CodecFeat *m) {
  if (m->e8_cnt <= 3095.500000000) {
    if (m->file_size <= 19104.000000000) {
      if (m->text_sz <= 4899.000000000) {
        if (m->data_ratio <= 0.063646499) {
          if (m->ascii_ratio_rodata <= 0.386225000) {
            return 1;
          } else {
            return 1;
          }
        } else {
          return 1;
        }
      } else {
        return 0;
      }
    } else {
      if (m->ret_cnt <= 623.500000000) {
        if (m->data_entropy <= 5.310740948) {
          if (m->rel_branch_ratio <= 0.935038984) {
            if (m->avg_rel32_abs <= 13867854.500000000) {
              return 1;
            } else {
              if (m->data_ratio <= 0.013881500) {
                return 1;
              } else {
                if (m->riprel_estimate <= 663.000000000) {
                  return 1;
                } else {
                  if (m->nop_ratio_text <= 0.003296000) {
                    return 1;
                  } else {
                    if (m->text_sz <= 62833.000000000) {
                      return 1;
                    } else {
                      return 1;
                    }
                  }
                }
              }
            }
          } else {
            if (m->text_entropy <= 6.100923061) {
              return 1;
            } else {
              return 1;
            }
          }
        } else {
          return 1;
        }
      } else {
        if (m->jcc32_cnt <= 498.000000000) {
          return 1;
        } else {
          if (m->bss_sz <= 384.000000000) {
            return 1;
          } else {
            if (m->ro_ptr_like_cnt <= 341.500000000) {
              return 1;
            } else {
              if (m->riprel_estimate <= 1284.000000000) {
                return 1;
              } else {
                if (m->max_rel32_abs <= 2145433984.000000000) {
                  return 1;
                } else {
                  return 1;
                }
              }
            }
          }
        }
      }
    }
  } else {
    if (m->data_ratio <= 0.025878999) {
      if (m->data_entropy <= 2.310584068) {
        if (m->avg_rel32_abs <= 80563612.000000000) {
          if (m->riprel_estimate <= 2634.500000000) {
            return 0;
          } else {
            return 0;
          }
        } else {
          if (m->branch_density_per_kb <= 30.682389259) {
            return 0;
          } else {
            if (m->nop_ratio_text <= 0.003487000) {
              return 1;
            } else {
              return 1;
            }
          }
        }
      } else {
        if (m->zeros_ratio_total <= 0.151970498) {
          return 0;
        } else {
          if (m->ascii_ratio_rodata <= 0.380718008) {
            return 1;
          } else {
            return 1;
          }
        }
      }
    } else {
      if (m->data_ratio <= 0.044974500) {
        if (m->align_pad_ratio <= 0.032773498) {
          if (m->text_entropy <= 6.333990097) {
            if (m->ro_sz <= 610736.000000000) {
              if (m->jcc32_cnt <= 1657.000000000) {
                return 1;
              } else {
                return 1;
              }
            } else {
              return 1;
            }
          } else {
            return 0;
          }
        } else {
          return 0;
        }
      } else {
        if (m->ro_ptr_like_cnt <= 5376.500000000) {
          if (m->rel32_intext_cnt <= 42082.500000000) {
            return 1;
          } else {
            return 1;
          }
        } else {
          if (m->jcc32_cnt <= 30133.500000000) {
            if (m->jcc32_cnt <= 19097.500000000) {
              return 1;
            } else {
              return 0;
            }
          } else {
            return 1;
          }
        }
      }
    }
  }
}

static inline int lzfse_dt_predict_from_pvec(const double *in) {
    lzfse_CodecFeat m; memset(&m, 0, sizeof(m));
    m.file_size = in[PP_FEAT_file_size];
    m.text_sz = in[PP_FEAT_text_sz];
    m.ro_sz = in[PP_FEAT_ro_sz];
    m.data_ratio = in[PP_FEAT_data_ratio];
    m.text_entropy = in[PP_FEAT_text_entropy];
    m.data_entropy = in[PP_FEAT_data_entropy];
    m.zeros_ratio_total = in[PP_FEAT_zeros_ratio_total];
    m.ascii_ratio_rodata = in[PP_FEAT_ascii_ratio_rodata];
    m.e8_cnt = in[PP_FEAT_e8_cnt];
    m.jcc32_cnt = in[PP_FEAT_jcc32_cnt];
    m.branch_density_per_kb = in[PP_FEAT_branch_density_per_kb];
    m.riprel_estimate = in[PP_FEAT_riprel_estimate];
    m.nop_ratio_text = in[PP_FEAT_nop_ratio_text];
    m.align_pad_ratio = in[PP_FEAT_align_pad_ratio];
    m.ro_ptr_like_cnt = in[PP_FEAT_ro_ptr_like_cnt];
    m.rel32_intext_cnt = in[PP_FEAT_rel32_intext_cnt];
    m.bss_sz = in[PP_FEAT_bss_sz];
    m.ret_cnt = in[PP_FEAT_ret_cnt];
    m.rel_branch_ratio = in[PP_FEAT_rel_branch_ratio];
    m.avg_rel32_abs = in[PP_FEAT_avg_rel32_abs];
    m.max_rel32_abs = in[PP_FEAT_max_rel32_abs];
    return lzfse_dt_core(&m);
}

#ifdef __cplusplus
}
#endif
