// Auto-generated by tools/ml/train_codec_predictor.py
#pragma once
// Returns 0 for BCJ, 1 for KANZIEXE
#ifdef __cplusplus
extern "C" {
#endif
#include "exe_predict_feature_index.h"

// Minimal feature struct (only used fields)
typedef struct {
    double file_size;
    double text_sz;
    double ro_sz;
    double text_ratio;
    double data_ratio;
    double text_entropy;
    double zeros_ratio_total;
    double zero_runs_32;
    double ascii_ratio_rodata;
    double e8_cnt;
    double e9_cnt;
    double ff_calljmp_cnt;
    double jcc32_cnt;
    double branch_density_per_kb;
    double riprel_estimate;
    double imm64_mov_cnt;
    double ro_ptr_like_cnt;
    double rel32_disp_entropy8;
    double ret_cnt;
    double rel_branch_ratio;
} lzham_CodecFeat;

static inline int lzham_dt_core(const lzham_CodecFeat *m) {
  if (m->e8_cnt <= 13477.000000000) {
    if (m->ff_calljmp_cnt <= 576.500000000) {
      if (m->file_size <= 19320.000000000) {
        if (m->text_sz <= 3357.000000000) {
          if (m->ro_sz <= 6394.000000000) {
            return 1;
          } else {
            return 1;
          }
        } else {
          return 0;
        }
      } else {
        if (m->file_size <= 156232.000000000) {
          if (m->zeros_ratio_total <= 0.164414503) {
            return 1;
          } else {
            if (m->riprel_estimate <= 1354.000000000) {
              if (m->e8_cnt <= 2298.000000000) {
                return 1;
              } else {
                return 1;
              }
            } else {
              return 1;
            }
          }
        } else {
          if (m->ascii_ratio_rodata <= 0.565062493) {
            if (m->rel_branch_ratio <= 0.897603005) {
              if (m->ro_sz <= 72750.000000000) {
                return 0;
              } else {
                return 1;
              }
            } else {
              if (m->branch_density_per_kb <= 41.797256470) {
                return 1;
              } else {
                if (m->rel32_disp_entropy8 <= 1.023810983) {
                  return 1;
                } else {
                  return 1;
                }
              }
            }
          } else {
            return 1;
          }
        }
      }
    } else {
      if (m->e9_cnt <= 822.500000000) {
        return 0;
      } else {
        if (m->ro_ptr_like_cnt <= 1948.500000000) {
          if (m->text_ratio <= 0.725248009) {
            if (m->text_entropy <= 6.156821012) {
              if (m->rel_branch_ratio <= 0.887938499) {
                return 1;
              } else {
                return 1;
              }
            } else {
              if (m->rel_branch_ratio <= 0.895452499) {
                if (m->data_ratio <= 0.046077000) {
                  return 1;
                } else {
                  return 1;
                }
              } else {
                return 1;
              }
            }
          } else {
            return 1;
          }
        } else {
          if (m->jcc32_cnt <= 1636.500000000) {
            if (m->data_ratio <= 0.038865499) {
              return 0;
            } else {
              return 1;
            }
          } else {
            if (m->text_ratio <= 0.536724508) {
              return 1;
            } else {
              return 1;
            }
          }
        }
      }
    }
  } else {
    if (m->data_ratio <= 0.120418500) {
      if (m->imm64_mov_cnt <= 877.500000000) {
        if (m->text_entropy <= 6.325184822) {
          if (m->e9_cnt <= 16190.500000000) {
            if (m->zero_runs_32 <= 6.000000000) {
              return 1;
            } else {
              if (m->zeros_ratio_total <= 0.188574001) {
                return 0;
              } else {
                return 0;
              }
            }
          } else {
            return 1;
          }
        } else {
          if (m->rel_branch_ratio <= 0.913329482) {
            if (m->rel_branch_ratio <= 0.906507492) {
              return 1;
            } else {
              return 1;
            }
          } else {
            return 0;
          }
        }
      } else {
        if (m->ro_ptr_like_cnt <= 43655.500000000) {
          if (m->e8_cnt <= 54725.000000000) {
            return 0;
          } else {
            return 0;
          }
        } else {
          return 0;
        }
      }
    } else {
      if (m->rel_branch_ratio <= 0.923776001) {
        if (m->ret_cnt <= 14943.500000000) {
          return 1;
        } else {
          return 0;
        }
      } else {
        return 1;
      }
    }
  }
}

static inline int lzham_dt_predict_from_pvec(const double *in) {
    lzham_CodecFeat m; memset(&m, 0, sizeof(m));
    m.file_size = in[PP_FEAT_file_size];
    m.text_sz = in[PP_FEAT_text_sz];
    m.ro_sz = in[PP_FEAT_ro_sz];
    m.text_ratio = in[PP_FEAT_text_ratio];
    m.data_ratio = in[PP_FEAT_data_ratio];
    m.text_entropy = in[PP_FEAT_text_entropy];
    m.zeros_ratio_total = in[PP_FEAT_zeros_ratio_total];
    m.zero_runs_32 = in[PP_FEAT_zero_runs_32];
    m.ascii_ratio_rodata = in[PP_FEAT_ascii_ratio_rodata];
    m.e8_cnt = in[PP_FEAT_e8_cnt];
    m.e9_cnt = in[PP_FEAT_e9_cnt];
    m.ff_calljmp_cnt = in[PP_FEAT_ff_calljmp_cnt];
    m.jcc32_cnt = in[PP_FEAT_jcc32_cnt];
    m.branch_density_per_kb = in[PP_FEAT_branch_density_per_kb];
    m.riprel_estimate = in[PP_FEAT_riprel_estimate];
    m.imm64_mov_cnt = in[PP_FEAT_imm64_mov_cnt];
    m.ro_ptr_like_cnt = in[PP_FEAT_ro_ptr_like_cnt];
    m.rel32_disp_entropy8 = in[PP_FEAT_rel32_disp_entropy8];
    m.ret_cnt = in[PP_FEAT_ret_cnt];
    m.rel_branch_ratio = in[PP_FEAT_rel_branch_ratio];
    return lzham_dt_core(&m);
}

#ifdef __cplusplus
}
#endif
