// Auto-generated by tools/ml/train_codec_predictor.py
#pragma once
// Returns 0 for BCJ, 1 for KANZIEXE
#ifdef __cplusplus
extern "C" {
#endif
#include "exe_predict_feature_index.h"

// Minimal feature struct (only used fields)
typedef struct {
    double data_sz;
    double text_ratio;
    double ro_ratio;
    double data_ratio;
    double text_entropy;
    double ro_entropy;
    double zero_runs_16;
    double zero_runs_32;
    double ascii_ratio_rodata;
    double e8_cnt;
    double eb_cnt;
    double jcc32_cnt;
    double branch_density_per_kb;
    double nop_ratio_text;
    double align_pad_ratio;
    double rel32_intext_ratio;
    double avg_rel32_abs;
} lzma_CodecFeat;

static inline int lzma_dt_core(const lzma_CodecFeat *m) {
  if (m->jcc32_cnt <= 1759.500000000) {
    if (m->data_sz <= 21376.000000000) {
      if (m->align_pad_ratio <= 0.004100500) {
        return 0;
      } else {
        if (m->ro_entropy <= 5.775323391) {
          return 0;
        } else {
          return 0;
        }
      }
    } else {
      if (m->ro_ratio <= 0.521724522) {
        if (m->nop_ratio_text <= 0.002399000) {
          return 0;
        } else {
          return 0;
        }
      } else {
        return 1;
      }
    }
  } else {
    if (m->data_ratio <= 0.040410999) {
      if (m->ro_entropy <= 5.119324684) {
        if (m->align_pad_ratio <= 0.023957500) {
          return 0;
        } else {
          return 1;
        }
      } else {
        if (m->text_entropy <= 6.342725515) {
          if (m->zero_runs_16 <= 186.500000000) {
            if (m->ascii_ratio_rodata <= 0.378791988) {
              return 1;
            } else {
              return 0;
            }
          } else {
            if (m->rel32_intext_ratio <= 0.919417500) {
              return 0;
            } else {
              if (m->avg_rel32_abs <= 72810168.000000000) {
                if (m->eb_cnt <= 1416.000000000) {
                  return 0;
                } else {
                  return 0;
                }
              } else {
                return 0;
              }
            }
          }
        } else {
          if (m->branch_density_per_kb <= 31.881275177) {
            return 0;
          } else {
            return 1;
          }
        }
      }
    } else {
      if (m->text_ratio <= 0.373850510) {
        if (m->e8_cnt <= 114527.500000000) {
          return 1;
        } else {
          return 1;
        }
      } else {
        if (m->zero_runs_32 <= 51.500000000) {
          if (m->jcc32_cnt <= 11554.000000000) {
            if (m->align_pad_ratio <= 0.027137499) {
              return 1;
            } else {
              if (m->data_ratio <= 0.079709500) {
                if (m->nop_ratio_text <= 0.002672500) {
                  return 0;
                } else {
                  return 0;
                }
              } else {
                return 1;
              }
            }
          } else {
            return 1;
          }
        } else {
          if (m->zero_runs_16 <= 2093.000000000) {
            if (m->rel32_intext_ratio <= 0.875257522) {
              return 0;
            } else {
              return 0;
            }
          } else {
            return 1;
          }
        }
      }
    }
  }
}

static inline int lzma_dt_predict_from_pvec(const double *in) {
    lzma_CodecFeat m; memset(&m, 0, sizeof(m));
    m.data_sz = in[PP_FEAT_data_sz];
    m.text_ratio = in[PP_FEAT_text_ratio];
    m.ro_ratio = in[PP_FEAT_ro_ratio];
    m.data_ratio = in[PP_FEAT_data_ratio];
    m.text_entropy = in[PP_FEAT_text_entropy];
    m.ro_entropy = in[PP_FEAT_ro_entropy];
    m.zero_runs_16 = in[PP_FEAT_zero_runs_16];
    m.zero_runs_32 = in[PP_FEAT_zero_runs_32];
    m.ascii_ratio_rodata = in[PP_FEAT_ascii_ratio_rodata];
    m.e8_cnt = in[PP_FEAT_e8_cnt];
    m.eb_cnt = in[PP_FEAT_eb_cnt];
    m.jcc32_cnt = in[PP_FEAT_jcc32_cnt];
    m.branch_density_per_kb = in[PP_FEAT_branch_density_per_kb];
    m.nop_ratio_text = in[PP_FEAT_nop_ratio_text];
    m.align_pad_ratio = in[PP_FEAT_align_pad_ratio];
    m.rel32_intext_ratio = in[PP_FEAT_rel32_intext_ratio];
    m.avg_rel32_abs = in[PP_FEAT_avg_rel32_abs];
    return lzma_dt_core(&m);
}

#ifdef __cplusplus
}
#endif
