// Auto-generated by tools/ml/train_codec_predictor.py
#pragma once
// Returns 0 for BCJ, 1 for KANZIEXE
#ifdef __cplusplus
extern "C" {
#endif
#include "exe_predict_feature_index.h"

// Minimal feature struct (only used fields)
typedef struct {
    double file_size;
    double ro_sz;
    double data_sz;
    double text_ratio;
    double ro_ratio;
    double data_ratio;
    double text_entropy;
    double zeros_ratio_total;
    double ascii_ratio_rodata;
    double ff_calljmp_cnt;
    double eb_cnt;
    double jcc32_cnt;
    double riprel_estimate;
    double rel32_intext_ratio;
    double rel32_intext_cnt;
    double rel32_disp_entropy8;
    double avg_rel32_abs;
    double max_rel32_abs;
} lzsa2_CodecFeat;

static inline int lzsa2_dt_core(const lzsa2_CodecFeat *m) {
  if (m->jcc32_cnt <= 786.000000000) {
    if (m->data_sz <= 16842.000000000) {
      if (m->jcc32_cnt <= 478.000000000) {
        if (m->zeros_ratio_total <= 0.213409998) {
          if (m->jcc32_cnt <= 391.000000000) {
            return 0;
          } else {
            return 0;
          }
        } else {
          if (m->data_sz <= 11568.000000000) {
            return 0;
          } else {
            return 0;
          }
        }
      } else {
        if (m->avg_rel32_abs <= 113605460.000000000) {
          if (m->rel32_intext_cnt <= 2571.500000000) {
            if (m->avg_rel32_abs <= 102984024.000000000) {
              return 0;
            } else {
              return 0;
            }
          } else {
            return 0;
          }
        } else {
          if (m->riprel_estimate <= 287.500000000) {
            return 1;
          } else {
            return 0;
          }
        }
      }
    } else {
      if (m->ro_sz <= 63700.000000000) {
        return 0;
      } else {
        return 1;
      }
    }
  } else {
    if (m->text_entropy <= 6.225164890) {
      if (m->jcc32_cnt <= 1378.500000000) {
        if (m->ff_calljmp_cnt <= 370.500000000) {
          if (m->ascii_ratio_rodata <= 0.509749472) {
            return 1;
          } else {
            return 0;
          }
        } else {
          if (m->text_ratio <= 0.528654516) {
            if (m->jcc32_cnt <= 1004.500000000) {
              return 0;
            } else {
              return 0;
            }
          } else {
            return 0;
          }
        }
      } else {
        if (m->zeros_ratio_total <= 0.178341001) {
          if (m->file_size <= 772436.000000000) {
            return 0;
          } else {
            return 1;
          }
        } else {
          if (m->ro_ratio <= 0.464628994) {
            if (m->rel32_disp_entropy8 <= 1.747256994) {
              if (m->data_ratio <= 0.020344000) {
                return 1;
              } else {
                return 1;
              }
            } else {
              return 1;
            }
          } else {
            return 0;
          }
        }
      }
    } else {
      if (m->max_rel32_abs <= 2126171392.000000000) {
        return 0;
      } else {
        if (m->text_ratio <= 0.778304994) {
          if (m->rel32_intext_ratio <= 0.848726988) {
            if (m->zeros_ratio_total <= 0.206415504) {
              if (m->data_ratio <= 0.031194999) {
                return 1;
              } else {
                return 0;
              }
            } else {
              return 1;
            }
          } else {
            if (m->text_entropy <= 6.244563580) {
              if (m->ascii_ratio_rodata <= 0.382271498) {
                return 1;
              } else {
                return 1;
              }
            } else {
              if (m->eb_cnt <= 18155.000000000) {
                if (m->ascii_ratio_rodata <= 0.296848997) {
                  return 1;
                } else {
                  return 1;
                }
              } else {
                return 1;
              }
            }
          }
        } else {
          return 0;
        }
      }
    }
  }
}

static inline int lzsa2_dt_predict_from_pvec(const double *in) {
    lzsa2_CodecFeat m; memset(&m, 0, sizeof(m));
    m.file_size = in[PP_FEAT_file_size];
    m.ro_sz = in[PP_FEAT_ro_sz];
    m.data_sz = in[PP_FEAT_data_sz];
    m.text_ratio = in[PP_FEAT_text_ratio];
    m.ro_ratio = in[PP_FEAT_ro_ratio];
    m.data_ratio = in[PP_FEAT_data_ratio];
    m.text_entropy = in[PP_FEAT_text_entropy];
    m.zeros_ratio_total = in[PP_FEAT_zeros_ratio_total];
    m.ascii_ratio_rodata = in[PP_FEAT_ascii_ratio_rodata];
    m.ff_calljmp_cnt = in[PP_FEAT_ff_calljmp_cnt];
    m.eb_cnt = in[PP_FEAT_eb_cnt];
    m.jcc32_cnt = in[PP_FEAT_jcc32_cnt];
    m.riprel_estimate = in[PP_FEAT_riprel_estimate];
    m.rel32_intext_ratio = in[PP_FEAT_rel32_intext_ratio];
    m.rel32_intext_cnt = in[PP_FEAT_rel32_intext_cnt];
    m.rel32_disp_entropy8 = in[PP_FEAT_rel32_disp_entropy8];
    m.avg_rel32_abs = in[PP_FEAT_avg_rel32_abs];
    m.max_rel32_abs = in[PP_FEAT_max_rel32_abs];
    return lzsa2_dt_core(&m);
}

#ifdef __cplusplus
}
#endif
