// Auto-generated by tools/ml/train_codec_predictor.py
#pragma once
// Returns 0 for BCJ, 1 for KANZIEXE
#ifdef __cplusplus
extern "C" {
#endif
#include "exe_predict_feature_index.h"

// Minimal feature struct (only used fields)
typedef struct {
    double file_size;
    double text_sz;
    double text_ratio;
    double ro_ratio;
    double data_ratio;
    double text_entropy;
    double zeros_ratio_total;
    double e8_cnt;
    double e9_cnt;
    double branch_density_per_kb;
    double imm64_mov_cnt;
    double align_pad_ratio;
    double rel32_intext_ratio;
    double rel32_intext_cnt;
    double rel32_disp_entropy8;
    double bss_sz;
} nz1_CodecFeat;

static inline int nz1_dt_core(const nz1_CodecFeat *m) {
  if (m->rel32_intext_cnt <= 19593.000000000) {
    if (m->data_ratio <= 0.011901000) {
      if (m->rel32_intext_cnt <= 5319.500000000) {
        return 1;
      } else {
        return 0;
      }
    } else {
      if (m->e8_cnt <= 6679.500000000) {
        if (m->ro_ratio <= 0.128240496) {
          if (m->rel32_disp_entropy8 <= 1.543320537) {
            return 1;
          } else {
            return 1;
          }
        } else {
          if (m->imm64_mov_cnt <= 153.500000000) {
            if (m->text_ratio <= 0.713198006) {
              if (m->align_pad_ratio <= 0.004727000) {
                return 1;
              } else {
                if (m->file_size <= 14860.000000000) {
                  if (m->text_sz <= 3817.000000000) {
                    if (m->zeros_ratio_total <= 0.356239006) {
                      return 1;
                    } else {
                      return 1;
                    }
                  } else {
                    return 1;
                  }
                } else {
                  return 1;
                }
              }
            } else {
              return 1;
            }
          } else {
            return 1;
          }
        }
      } else {
        if (m->bss_sz <= 1253.500000000) {
          return 1;
        } else {
          if (m->e9_cnt <= 2577.000000000) {
            return 1;
          } else {
            return 1;
          }
        }
      }
    }
  } else {
    if (m->rel32_disp_entropy8 <= 1.476692021) {
      if (m->data_ratio <= 0.044113500) {
        if (m->e8_cnt <= 26652.500000000) {
          return 0;
        } else {
          return 0;
        }
      } else {
        return 0;
      }
    } else {
      if (m->zeros_ratio_total <= 0.159293003) {
        return 0;
      } else {
        if (m->branch_density_per_kb <= 38.387683868) {
          if (m->text_entropy <= 6.273996353) {
            return 1;
          } else {
            if (m->bss_sz <= 39778.000000000) {
              return 1;
            } else {
              if (m->rel32_intext_ratio <= 0.840511501) {
                return 1;
              } else {
                return 1;
              }
            }
          }
        } else {
          return 0;
        }
      }
    }
  }
}

static inline int nz1_dt_predict_from_pvec(const double *in) {
    nz1_CodecFeat m; memset(&m, 0, sizeof(m));
    m.file_size = in[PP_FEAT_file_size];
    m.text_sz = in[PP_FEAT_text_sz];
    m.text_ratio = in[PP_FEAT_text_ratio];
    m.ro_ratio = in[PP_FEAT_ro_ratio];
    m.data_ratio = in[PP_FEAT_data_ratio];
    m.text_entropy = in[PP_FEAT_text_entropy];
    m.zeros_ratio_total = in[PP_FEAT_zeros_ratio_total];
    m.e8_cnt = in[PP_FEAT_e8_cnt];
    m.e9_cnt = in[PP_FEAT_e9_cnt];
    m.branch_density_per_kb = in[PP_FEAT_branch_density_per_kb];
    m.imm64_mov_cnt = in[PP_FEAT_imm64_mov_cnt];
    m.align_pad_ratio = in[PP_FEAT_align_pad_ratio];
    m.rel32_intext_ratio = in[PP_FEAT_rel32_intext_ratio];
    m.rel32_intext_cnt = in[PP_FEAT_rel32_intext_cnt];
    m.rel32_disp_entropy8 = in[PP_FEAT_rel32_disp_entropy8];
    m.bss_sz = in[PP_FEAT_bss_sz];
    return nz1_dt_core(&m);
}

#ifdef __cplusplus
}
#endif
