// Auto-generated by tools/ml/train_pp_predictor.py
#pragma once
// Returns 0 for BCJ, 1 for KANZIEXE
#ifdef __cplusplus
extern "C" {
#endif
#include "exe_predict_feature_index.h"

// Minimal feature struct (only used fields)
typedef struct {
    double ro_sz;
    double ro_entropy;
    double zero_runs_16;
    double zero_runs_32;
    double e9_cnt;
    double jcc32_cnt;
    double branch_density_per_kb;
    double nop_ratio_text;
    double rel32_intext_ratio;
    double bss_sz;
    double ret_cnt;
    double rel_branch_ratio;
    double avg_rel32_abs;
} PpFeat;

static inline int pp_dt_core(const PpFeat *m) {
  if (m->jcc32_cnt <= 1047.500000000) {
    if (m->jcc32_cnt <= 862.500000000) {
      if (m->ro_sz <= 116170.000000000) {
        if (m->zero_runs_16 <= 346.000000000) {
          if (m->e9_cnt <= 630.500000000) {
            return 0;
          } else {
            if (m->bss_sz <= 15724.000000000) {
              return 0;
            } else {
              return 0;
            }
          }
        } else {
          return 0;
        }
      } else {
        if (m->rel_branch_ratio <= 0.895068496) {
          return 0;
        } else {
          return 1;
        }
      }
    } else {
      if (m->ro_entropy <= 5.239047289) {
        if (m->ret_cnt <= 597.500000000) {
          return 1;
        } else {
          return 0;
        }
      } else {
        return 0;
      }
    }
  } else {
    if (m->e9_cnt <= 936.000000000) {
      if (m->branch_density_per_kb <= 31.591972351) {
        return 1;
      } else {
        return 0;
      }
    } else {
      if (m->avg_rel32_abs <= 52301886.000000000) {
        if (m->zero_runs_32 <= 13.500000000) {
          return 0;
        } else {
          return 1;
        }
      } else {
        if (m->jcc32_cnt <= 1503.000000000) {
          if (m->nop_ratio_text <= 0.003190000) {
            if (m->rel32_intext_ratio <= 0.865579009) {
              return 1;
            } else {
              return 1;
            }
          } else {
            return 1;
          }
        } else {
          if (m->avg_rel32_abs <= 202205392.000000000) {
            return 1;
          } else {
            return 1;
          }
        }
      }
    }
  }
}

static inline int pp_dt_predict_from_pvec(const double *in) {
    PpFeat m; memset(&m, 0, sizeof(m));
    m.ro_sz = in[PP_FEAT_ro_sz];
    m.ro_entropy = in[PP_FEAT_ro_entropy];
    m.zero_runs_16 = in[PP_FEAT_zero_runs_16];
    m.zero_runs_32 = in[PP_FEAT_zero_runs_32];
    m.e9_cnt = in[PP_FEAT_e9_cnt];
    m.jcc32_cnt = in[PP_FEAT_jcc32_cnt];
    m.branch_density_per_kb = in[PP_FEAT_branch_density_per_kb];
    m.nop_ratio_text = in[PP_FEAT_nop_ratio_text];
    m.rel32_intext_ratio = in[PP_FEAT_rel32_intext_ratio];
    m.bss_sz = in[PP_FEAT_bss_sz];
    m.ret_cnt = in[PP_FEAT_ret_cnt];
    m.rel_branch_ratio = in[PP_FEAT_rel_branch_ratio];
    m.avg_rel32_abs = in[PP_FEAT_avg_rel32_abs];
    return pp_dt_core(&m);
}

#ifdef __cplusplus
}
#endif
