// Auto-generated by tools/ml/train_codec_predictor.py
#pragma once
// Returns 0 for BCJ, 1 for KANZIEXE
#ifdef __cplusplus
extern "C" {
#endif
#include "exe_predict_feature_index.h"

// Minimal feature struct (only used fields)
typedef struct {
    double ro_sz;
    double data_sz;
    double text_ratio;
    double ro_ratio;
    double data_ratio;
    double text_entropy;
    double ro_entropy;
    double e8_cnt;
    double ff_calljmp_cnt;
    double eb_cnt;
    double jcc32_cnt;
    double branch_density_per_kb;
    double nop_ratio_text;
    double imm64_mov_cnt;
    double rel32_disp_entropy8;
    double bss_sz;
    double max_rel32_abs;
} qlz_CodecFeat;

static inline int qlz_dt_core(const qlz_CodecFeat *m) {
  if (m->jcc32_cnt <= 1225.000000000) {
    if (m->data_sz <= 20900.000000000) {
      if (m->jcc32_cnt <= 794.500000000) {
        if (m->data_sz <= 17088.000000000) {
          if (m->data_sz <= 8740.000000000) {
            return 0;
          } else {
            if (m->bss_sz <= 1102.000000000) {
              return 0;
            } else {
              return 0;
            }
          }
        } else {
          return 0;
        }
      } else {
        if (m->ro_entropy <= 4.791739941) {
          return 1;
        } else {
          if (m->rel32_disp_entropy8 <= 1.553369522) {
            if (m->ff_calljmp_cnt <= 317.000000000) {
              return 0;
            } else {
              return 0;
            }
          } else {
            if (m->rel32_disp_entropy8 <= 1.647455454) {
              return 1;
            } else {
              return 0;
            }
          }
        }
      }
    } else {
      if (m->ro_sz <= 104366.000000000) {
        if (m->ro_entropy <= 4.702725410) {
          return 0;
        } else {
          return 0;
        }
      } else {
        return 1;
      }
    }
  } else {
    if (m->branch_density_per_kb <= 43.766302109) {
      if (m->nop_ratio_text <= 0.003349000) {
        if (m->max_rel32_abs <= 2145763712.000000000) {
          if (m->eb_cnt <= 402.500000000) {
            return 1;
          } else {
            if (m->jcc32_cnt <= 2736.000000000) {
              if (m->e8_cnt <= 3755.500000000) {
                return 1;
              } else {
                return 0;
              }
            } else {
              return 1;
            }
          }
        } else {
          if (m->ro_ratio <= 0.172105499) {
            return 0;
          } else {
            if (m->text_ratio <= 0.529700011) {
              return 1;
            } else {
              if (m->text_ratio <= 0.623369008) {
                if (m->text_ratio <= 0.583469003) {
                  if (m->imm64_mov_cnt <= 159.500000000) {
                    return 1;
                  } else {
                    return 1;
                  }
                } else {
                  return 0;
                }
              } else {
                if (m->nop_ratio_text <= 0.002287000) {
                  return 1;
                } else {
                  return 1;
                }
              }
            }
          }
        }
      } else {
        if (m->data_ratio <= 0.061492000) {
          if (m->text_entropy <= 6.222861528) {
            return 0;
          } else {
            return 0;
          }
        } else {
          return 1;
        }
      }
    } else {
      if (m->ro_entropy <= 5.032116413) {
        if (m->text_entropy <= 6.189653635) {
          return 0;
        } else {
          return 1;
        }
      } else {
        if (m->ro_entropy <= 5.345686913) {
          return 0;
        } else {
          return 0;
        }
      }
    }
  }
}

static inline int qlz_dt_predict_from_pvec(const double *in) {
    qlz_CodecFeat m; memset(&m, 0, sizeof(m));
    m.ro_sz = in[PP_FEAT_ro_sz];
    m.data_sz = in[PP_FEAT_data_sz];
    m.text_ratio = in[PP_FEAT_text_ratio];
    m.ro_ratio = in[PP_FEAT_ro_ratio];
    m.data_ratio = in[PP_FEAT_data_ratio];
    m.text_entropy = in[PP_FEAT_text_entropy];
    m.ro_entropy = in[PP_FEAT_ro_entropy];
    m.e8_cnt = in[PP_FEAT_e8_cnt];
    m.ff_calljmp_cnt = in[PP_FEAT_ff_calljmp_cnt];
    m.eb_cnt = in[PP_FEAT_eb_cnt];
    m.jcc32_cnt = in[PP_FEAT_jcc32_cnt];
    m.branch_density_per_kb = in[PP_FEAT_branch_density_per_kb];
    m.nop_ratio_text = in[PP_FEAT_nop_ratio_text];
    m.imm64_mov_cnt = in[PP_FEAT_imm64_mov_cnt];
    m.rel32_disp_entropy8 = in[PP_FEAT_rel32_disp_entropy8];
    m.bss_sz = in[PP_FEAT_bss_sz];
    m.max_rel32_abs = in[PP_FEAT_max_rel32_abs];
    return qlz_dt_core(&m);
}

#ifdef __cplusplus
}
#endif
