// Auto-generated by tools/ml/train_codec_predictor.py
#pragma once
// Returns 0 for BCJ, 1 for KANZIEXE
#ifdef __cplusplus
extern "C" {
#endif
#include "exe_predict_feature_index.h"

// Minimal feature struct (only used fields)
typedef struct {
    double file_size;
    double ro_sz;
    double data_sz;
    double ro_ratio;
    double data_ratio;
    double ro_entropy;
    double zeros_ratio_total;
    double ascii_ratio_rodata;
    double e8_cnt;
    double branch_density_per_kb;
    double imm64_mov_cnt;
    double align_pad_ratio;
    double rel32_intext_ratio;
    double bss_sz;
} rnc_CodecFeat;

static inline int rnc_dt_core(const rnc_CodecFeat *m) {
  if (m->data_ratio <= 0.010230000) {
    if (m->ro_sz <= 648974.500000000) {
      return 1;
    } else {
      return 1;
    }
  } else {
    if (m->file_size <= 163020.000000000) {
      if (m->zeros_ratio_total <= 0.157609001) {
        return 1;
      } else {
        if (m->e8_cnt <= 2334.000000000) {
          return 1;
        } else {
          if (m->ro_ratio <= 0.344858497) {
            return 1;
          } else {
            return 1;
          }
        }
      }
    } else {
      if (m->imm64_mov_cnt <= 1.500000000) {
        return 1;
      } else {
        if (m->branch_density_per_kb <= 24.071109772) {
          return 1;
        } else {
          if (m->bss_sz <= 364.000000000) {
            if (m->ascii_ratio_rodata <= 0.418112502) {
              return 1;
            } else {
              return 1;
            }
          } else {
            if (m->ro_ratio <= 0.209764995) {
              if (m->data_sz <= 181716.000000000) {
                return 1;
              } else {
                return 1;
              }
            } else {
              if (m->ro_entropy <= 6.169358015) {
                if (m->rel32_intext_ratio <= 0.955580980) {
                  if (m->align_pad_ratio <= 0.043252999) {
                    return 1;
                  } else {
                    return 1;
                  }
                } else {
                  return 1;
                }
              } else {
                return 1;
              }
            }
          }
        }
      }
    }
  }
}

static inline int rnc_dt_predict_from_pvec(const double *in) {
    rnc_CodecFeat m; memset(&m, 0, sizeof(m));
    m.file_size = in[PP_FEAT_file_size];
    m.ro_sz = in[PP_FEAT_ro_sz];
    m.data_sz = in[PP_FEAT_data_sz];
    m.ro_ratio = in[PP_FEAT_ro_ratio];
    m.data_ratio = in[PP_FEAT_data_ratio];
    m.ro_entropy = in[PP_FEAT_ro_entropy];
    m.zeros_ratio_total = in[PP_FEAT_zeros_ratio_total];
    m.ascii_ratio_rodata = in[PP_FEAT_ascii_ratio_rodata];
    m.e8_cnt = in[PP_FEAT_e8_cnt];
    m.branch_density_per_kb = in[PP_FEAT_branch_density_per_kb];
    m.imm64_mov_cnt = in[PP_FEAT_imm64_mov_cnt];
    m.align_pad_ratio = in[PP_FEAT_align_pad_ratio];
    m.rel32_intext_ratio = in[PP_FEAT_rel32_intext_ratio];
    m.bss_sz = in[PP_FEAT_bss_sz];
    return rnc_dt_core(&m);
}

#ifdef __cplusplus
}
#endif
