// Auto-generated by tools/ml/train_codec_predictor.py
#pragma once
// Returns 0 for BCJ, 1 for KANZIEXE
#ifdef __cplusplus
extern "C" {
#endif
#include "exe_predict_feature_index.h"

// Minimal feature struct (only used fields)
typedef struct {
    double file_size;
    double data_sz;
    double data_ratio;
    double text_entropy;
    double ro_entropy;
    double data_entropy;
    double zeros_ratio_total;
    double ascii_ratio_rodata;
    double e9_cnt;
    double eb_cnt;
    double jcc32_cnt;
    double branch_density_per_kb;
    double nop_ratio_text;
    double ret_cnt;
} shrinkler_CodecFeat;

static inline int shrinkler_dt_core(const shrinkler_CodecFeat *m) {
  if (m->data_sz <= 33966.000000000) {
    if (m->eb_cnt <= 1625.000000000) {
      if (m->jcc32_cnt <= 1752.500000000) {
        if (m->data_sz <= 18568.000000000) {
          return 0;
        } else {
          if (m->ret_cnt <= 622.000000000) {
            return 0;
          } else {
            return 0;
          }
        }
      } else {
        if (m->nop_ratio_text <= 0.001847500) {
          return 1;
        } else {
          if (m->file_size <= 270044.000000000) {
            return 0;
          } else {
            return 0;
          }
        }
      }
    } else {
      if (m->zeros_ratio_total <= 0.161112003) {
        return 0;
      } else {
        return 1;
      }
    }
  } else {
    if (m->eb_cnt <= 5879.000000000) {
      if (m->ascii_ratio_rodata <= 0.357243493) {
        if (m->data_sz <= 60230.000000000) {
          return 0;
        } else {
          if (m->jcc32_cnt <= 11545.500000000) {
            return 1;
          } else {
            return 1;
          }
        }
      } else {
        if (m->e9_cnt <= 1268.500000000) {
          return 0;
        } else {
          if (m->data_ratio <= 0.080164500) {
            if (m->branch_density_per_kb <= 37.371702194) {
              return 1;
            } else {
              if (m->ro_entropy <= 5.479673386) {
                return 0;
              } else {
                return 0;
              }
            }
          } else {
            if (m->data_entropy <= 1.937008500) {
              return 0;
            } else {
              return 1;
            }
          }
        }
      }
    } else {
      if (m->ro_entropy <= 4.757178068) {
        return 0;
      } else {
        if (m->text_entropy <= 6.361671686) {
          return 0;
        } else {
          return 0;
        }
      }
    }
  }
}

static inline int shrinkler_dt_predict_from_pvec(const double *in) {
    shrinkler_CodecFeat m; memset(&m, 0, sizeof(m));
    m.file_size = in[PP_FEAT_file_size];
    m.data_sz = in[PP_FEAT_data_sz];
    m.data_ratio = in[PP_FEAT_data_ratio];
    m.text_entropy = in[PP_FEAT_text_entropy];
    m.ro_entropy = in[PP_FEAT_ro_entropy];
    m.data_entropy = in[PP_FEAT_data_entropy];
    m.zeros_ratio_total = in[PP_FEAT_zeros_ratio_total];
    m.ascii_ratio_rodata = in[PP_FEAT_ascii_ratio_rodata];
    m.e9_cnt = in[PP_FEAT_e9_cnt];
    m.eb_cnt = in[PP_FEAT_eb_cnt];
    m.jcc32_cnt = in[PP_FEAT_jcc32_cnt];
    m.branch_density_per_kb = in[PP_FEAT_branch_density_per_kb];
    m.nop_ratio_text = in[PP_FEAT_nop_ratio_text];
    m.ret_cnt = in[PP_FEAT_ret_cnt];
    return shrinkler_dt_core(&m);
}

#ifdef __cplusplus
}
#endif
