// Auto-generated by tools/ml/train_codec_predictor.py
#pragma once
// Returns 0 for BCJ, 1 for KANZIEXE
#ifdef __cplusplus
extern "C" {
#endif
#include "exe_predict_feature_index.h"

// Minimal feature struct (only used fields)
typedef struct {
    double ro_sz;
    double text_ratio;
    double ro_entropy;
    double zero_runs_16;
    double zero_runs_32;
    double e8_cnt;
    double e9_cnt;
    double eb_cnt;
    double jcc32_cnt;
    double branch_density_per_kb;
    double ro_ptr_like_cnt;
    double rel32_intext_ratio;
    double rel32_disp_entropy8;
    double bss_sz;
    double ret_cnt;
    double rel_branch_ratio;
    double avg_rel32_abs;
} snappy_CodecFeat;

static inline int snappy_dt_core(const snappy_CodecFeat *m) {
  if (m->e9_cnt <= 628.500000000) {
    if (m->ro_sz <= 38154.000000000) {
      if (m->e9_cnt <= 556.500000000) {
        if (m->zero_runs_16 <= 139.500000000) {
          return 0;
        } else {
          if (m->jcc32_cnt <= 408.000000000) {
            return 0;
          } else {
            return 0;
          }
        }
      } else {
        return 0;
      }
    } else {
      if (m->ro_entropy <= 4.936810970) {
        if (m->eb_cnt <= 103.000000000) {
          return 0;
        } else {
          if (m->rel_branch_ratio <= 0.883326501) {
            return 1;
          } else {
            return 1;
          }
        }
      } else {
        if (m->rel32_intext_ratio <= 0.948272020) {
          return 0;
        } else {
          return 0;
        }
      }
    }
  } else {
    if (m->ret_cnt <= 830.500000000) {
      if (m->rel32_intext_ratio <= 0.934248477) {
        if (m->bss_sz <= 35586.000000000) {
          if (m->eb_cnt <= 258.000000000) {
            if (m->ro_ptr_like_cnt <= 506.500000000) {
              if (m->branch_density_per_kb <= 34.887527466) {
                return 1;
              } else {
                return 1;
              }
            } else {
              return 1;
            }
          } else {
            if (m->bss_sz <= 1136.000000000) {
              return 0;
            } else {
              if (m->rel_branch_ratio <= 0.914944500) {
                return 1;
              } else {
                return 1;
              }
            }
          }
        } else {
          return 0;
        }
      } else {
        if (m->bss_sz <= 816.000000000) {
          if (m->rel32_disp_entropy8 <= 0.739223003) {
            return 0;
          } else {
            return 0;
          }
        } else {
          return 1;
        }
      }
    } else {
      if (m->ro_entropy <= 6.234170914) {
        if (m->eb_cnt <= 27339.000000000) {
          if (m->ro_ptr_like_cnt <= 751.000000000) {
            if (m->e8_cnt <= 4737.000000000) {
              if (m->text_ratio <= 0.636958003) {
                return 1;
              } else {
                if (m->rel32_disp_entropy8 <= 1.724644482) {
                  return 0;
                } else {
                  return 1;
                }
              }
            } else {
              return 0;
            }
          } else {
            if (m->avg_rel32_abs <= 48512900.000000000) {
              return 1;
            } else {
              if (m->zero_runs_32 <= 1.500000000) {
                return 1;
              } else {
                if (m->e9_cnt <= 1865.000000000) {
                  if (m->e8_cnt <= 4297.000000000) {
                    return 1;
                  } else {
                    return 1;
                  }
                } else {
                  return 1;
                }
              }
            }
          }
        } else {
          return 1;
        }
      } else {
        if (m->avg_rel32_abs <= 96233988.000000000) {
          return 0;
        } else {
          return 0;
        }
      }
    }
  }
}

static inline int snappy_dt_predict_from_pvec(const double *in) {
    snappy_CodecFeat m; memset(&m, 0, sizeof(m));
    m.ro_sz = in[PP_FEAT_ro_sz];
    m.text_ratio = in[PP_FEAT_text_ratio];
    m.ro_entropy = in[PP_FEAT_ro_entropy];
    m.zero_runs_16 = in[PP_FEAT_zero_runs_16];
    m.zero_runs_32 = in[PP_FEAT_zero_runs_32];
    m.e8_cnt = in[PP_FEAT_e8_cnt];
    m.e9_cnt = in[PP_FEAT_e9_cnt];
    m.eb_cnt = in[PP_FEAT_eb_cnt];
    m.jcc32_cnt = in[PP_FEAT_jcc32_cnt];
    m.branch_density_per_kb = in[PP_FEAT_branch_density_per_kb];
    m.ro_ptr_like_cnt = in[PP_FEAT_ro_ptr_like_cnt];
    m.rel32_intext_ratio = in[PP_FEAT_rel32_intext_ratio];
    m.rel32_disp_entropy8 = in[PP_FEAT_rel32_disp_entropy8];
    m.bss_sz = in[PP_FEAT_bss_sz];
    m.ret_cnt = in[PP_FEAT_ret_cnt];
    m.rel_branch_ratio = in[PP_FEAT_rel_branch_ratio];
    m.avg_rel32_abs = in[PP_FEAT_avg_rel32_abs];
    return snappy_dt_core(&m);
}

#ifdef __cplusplus
}
#endif
