// Auto-generated by tools/ml/train_codec_predictor.py
#pragma once
// Returns 0 for BCJ, 1 for KANZIEXE
#ifdef __cplusplus
extern "C" {
#endif
#include "exe_predict_feature_index.h"

// Minimal feature struct (only used fields)
typedef struct {
    double file_size;
    double data_sz;
    double text_ratio;
    double ro_entropy;
    double zero_runs_16;
    double e9_cnt;
    double jcc32_cnt;
    double branch_density_per_kb;
    double rel32_intext_ratio;
    double rel32_intext_cnt;
    double bss_sz;
    double ret_cnt;
    double max_rel32_abs;
} sc_CodecFeat;

static inline int sc_dt_core(const sc_CodecFeat *m) {
  if (m->jcc32_cnt <= 1047.500000000) {
    if (m->rel32_intext_cnt <= 5501.500000000) {
      if (m->jcc32_cnt <= 862.500000000) {
        if (m->file_size <= 209512.000000000) {
          if (m->e9_cnt <= 1027.500000000) {
            if (m->e9_cnt <= 630.500000000) {
              return 0;
            } else {
              if (m->rel32_intext_ratio <= 0.901846021) {
                return 0;
              } else {
                return 0;
              }
            }
          } else {
            return 0;
          }
        } else {
          return 0;
        }
      } else {
        if (m->zero_runs_16 <= 138.500000000) {
          return 1;
        } else {
          return 0;
        }
      }
    } else {
      return 1;
    }
  } else {
    if (m->e9_cnt <= 936.000000000) {
      if (m->text_ratio <= 0.584245503) {
        return 1;
      } else {
        return 0;
      }
    } else {
      if (m->data_sz <= 2924.000000000) {
        return 1;
      } else {
        if (m->max_rel32_abs <= 2130546944.000000000) {
          if (m->ro_entropy <= 5.129122972) {
            return 1;
          } else {
            return 1;
          }
        } else {
          if (m->branch_density_per_kb <= 27.445077896) {
            if (m->bss_sz <= 29250.000000000) {
              return 1;
            } else {
              return 1;
            }
          } else {
            if (m->ret_cnt <= 928.500000000) {
              if (m->bss_sz <= 1266.000000000) {
                return 1;
              } else {
                return 1;
              }
            } else {
              return 1;
            }
          }
        }
      }
    }
  }
}

static inline int sc_dt_predict_from_pvec(const double *in) {
    sc_CodecFeat m; memset(&m, 0, sizeof(m));
    m.file_size = in[PP_FEAT_file_size];
    m.data_sz = in[PP_FEAT_data_sz];
    m.text_ratio = in[PP_FEAT_text_ratio];
    m.ro_entropy = in[PP_FEAT_ro_entropy];
    m.zero_runs_16 = in[PP_FEAT_zero_runs_16];
    m.e9_cnt = in[PP_FEAT_e9_cnt];
    m.jcc32_cnt = in[PP_FEAT_jcc32_cnt];
    m.branch_density_per_kb = in[PP_FEAT_branch_density_per_kb];
    m.rel32_intext_ratio = in[PP_FEAT_rel32_intext_ratio];
    m.rel32_intext_cnt = in[PP_FEAT_rel32_intext_cnt];
    m.bss_sz = in[PP_FEAT_bss_sz];
    m.ret_cnt = in[PP_FEAT_ret_cnt];
    m.max_rel32_abs = in[PP_FEAT_max_rel32_abs];
    return sc_dt_core(&m);
}

#ifdef __cplusplus
}
#endif
