// Auto-generated by tools/ml/train_codec_predictor.py
#pragma once
// Returns 0 for BCJ, 1 for KANZIEXE
#ifdef __cplusplus
extern "C" {
#endif
#include "exe_predict_feature_index.h"

// Minimal feature struct (only used fields)
typedef struct {
    double ro_sz;
    double data_sz;
    double ro_ratio;
    double data_ratio;
    double text_entropy;
    double ro_entropy;
    double data_entropy;
    double ascii_ratio_rodata;
    double e8_cnt;
    double ff_calljmp_cnt;
    double jcc32_cnt;
    double branch_density_per_kb;
    double riprel_estimate;
    double align_pad_ratio;
    double rel32_disp_entropy8;
    double rel_branch_ratio;
    double avg_rel32_abs;
} zstd_CodecFeat;

static inline int zstd_dt_core(const zstd_CodecFeat *m) {
  if (m->jcc32_cnt <= 1759.500000000) {
    if (m->data_sz <= 20888.000000000) {
      if (m->ro_entropy <= 6.369294167) {
        return 0;
      } else {
        return 0;
      }
    } else {
      if (m->ro_ratio <= 0.315656006) {
        return 0;
      } else {
        if (m->data_ratio <= 0.125594001) {
          return 0;
        } else {
          return 1;
        }
      }
    }
  } else {
    if (m->e8_cnt <= 74829.500000000) {
      if (m->data_ratio <= 0.038114000) {
        if (m->data_entropy <= 2.523479939) {
          if (m->ro_sz <= 54116.000000000) {
            return 1;
          } else {
            if (m->text_entropy <= 6.272155046) {
              if (m->data_entropy <= 2.210701466) {
                return 0;
              } else {
                return 0;
              }
            } else {
              if (m->rel32_disp_entropy8 <= 1.730861485) {
                return 1;
              } else {
                return 0;
              }
            }
          }
        } else {
          if (m->ff_calljmp_cnt <= 4499.500000000) {
            if (m->rel_branch_ratio <= 0.920547009) {
              return 1;
            } else {
              return 1;
            }
          } else {
            return 0;
          }
        }
      } else {
        if (m->rel32_disp_entropy8 <= 1.323097527) {
          return 0;
        } else {
          if (m->riprel_estimate <= 16307.500000000) {
            if (m->branch_density_per_kb <= 33.614885330) {
              if (m->avg_rel32_abs <= 119071908.000000000) {
                return 0;
              } else {
                return 1;
              }
            } else {
              if (m->align_pad_ratio <= 0.033794500) {
                if (m->text_entropy <= 6.356895447) {
                  return 1;
                } else {
                  return 1;
                }
              } else {
                return 1;
              }
            }
          } else {
            return 1;
          }
        }
      }
    } else {
      if (m->ro_entropy <= 4.787156582) {
        return 0;
      } else {
        if (m->ascii_ratio_rodata <= 0.380603999) {
          return 0;
        } else {
          return 0;
        }
      }
    }
  }
}

static inline int zstd_dt_predict_from_pvec(const double *in) {
    zstd_CodecFeat m; memset(&m, 0, sizeof(m));
    m.ro_sz = in[PP_FEAT_ro_sz];
    m.data_sz = in[PP_FEAT_data_sz];
    m.ro_ratio = in[PP_FEAT_ro_ratio];
    m.data_ratio = in[PP_FEAT_data_ratio];
    m.text_entropy = in[PP_FEAT_text_entropy];
    m.ro_entropy = in[PP_FEAT_ro_entropy];
    m.data_entropy = in[PP_FEAT_data_entropy];
    m.ascii_ratio_rodata = in[PP_FEAT_ascii_ratio_rodata];
    m.e8_cnt = in[PP_FEAT_e8_cnt];
    m.ff_calljmp_cnt = in[PP_FEAT_ff_calljmp_cnt];
    m.jcc32_cnt = in[PP_FEAT_jcc32_cnt];
    m.branch_density_per_kb = in[PP_FEAT_branch_density_per_kb];
    m.riprel_estimate = in[PP_FEAT_riprel_estimate];
    m.align_pad_ratio = in[PP_FEAT_align_pad_ratio];
    m.rel32_disp_entropy8 = in[PP_FEAT_rel32_disp_entropy8];
    m.rel_branch_ratio = in[PP_FEAT_rel_branch_ratio];
    m.avg_rel32_abs = in[PP_FEAT_avg_rel32_abs];
    return zstd_dt_core(&m);
}

#ifdef __cplusplus
}
#endif
