// Auto-generated by tools/ml/train_codec_predictor.py
#pragma once
// Returns 0 for BCJ, 1 for KANZIEXE
#ifdef __cplusplus
extern "C" {
#endif
#include "exe_predict_feature_index.h"

// Minimal feature struct (only used fields)
typedef struct {
    double file_size;
    double text_sz;
    double ro_sz;
    double text_ratio;
    double ro_ratio;
    double data_ratio;
    double text_entropy;
    double ro_entropy;
    double ascii_ratio_rodata;
    double e8_cnt;
    double e9_cnt;
    double ff_calljmp_cnt;
    double eb_cnt;
    double jcc32_cnt;
    double branch_density_per_kb;
    double nop_ratio_text;
    double imm64_mov_cnt;
    double align_pad_ratio;
    double rel32_disp_entropy8;
    double bss_sz;
    double ret_cnt;
    double rel_branch_ratio;
    double max_rel32_abs;
} zstd_CodecFeat;

static inline int zstd_dt_core(const zstd_CodecFeat *m) {
  if (m->jcc32_cnt <= 137.000000000) {
    if (m->ro_sz <= 25648.000000000) {
      if (m->jcc32_cnt <= 64.500000000) {
        if (m->text_entropy <= 6.085532904) {
          if (m->align_pad_ratio <= 0.020676000) {
            return 0;
          } else {
            return 0;
          }
        } else {
          return 0;
        }
      } else {
        if (m->ret_cnt <= 77.500000000) {
          if (m->ff_calljmp_cnt <= 61.500000000) {
            if (m->e9_cnt <= 98.500000000) {
              return 1;
            } else {
              return 1;
            }
          } else {
            if (m->ascii_ratio_rodata <= 0.372329503) {
              if (m->jcc32_cnt <= 99.000000000) {
                return 0;
              } else {
                return 1;
              }
            } else {
              if (m->ret_cnt <= 52.500000000) {
                if (m->file_size <= 31044.000000000) {
                  if (m->eb_cnt <= 24.500000000) {
                    return 0;
                  } else {
                    return 1;
                  }
                } else {
                  return 0;
                }
              } else {
                if (m->text_entropy <= 5.950313091) {
                  return 0;
                } else {
                  return 0;
                }
              }
            }
          }
        } else {
          if (m->max_rel32_abs <= 2061309632.000000000) {
            return 0;
          } else {
            if (m->text_sz <= 13321.000000000) {
              if (m->data_ratio <= 0.043094000) {
                return 0;
              } else {
                return 0;
              }
            } else {
              return 0;
            }
          }
        }
      }
    } else {
      return 1;
    }
  } else {
    if (m->ret_cnt <= 21863.500000000) {
      if (m->jcc32_cnt <= 247.500000000) {
        if (m->imm64_mov_cnt <= 6.500000000) {
          if (m->align_pad_ratio <= 0.016104001) {
            if (m->max_rel32_abs <= 2097151936.000000000) {
              return 1;
            } else {
              return 1;
            }
          } else {
            if (m->e8_cnt <= 348.500000000) {
              if (m->jcc32_cnt <= 150.500000000) {
                return 0;
              } else {
                if (m->e9_cnt <= 184.500000000) {
                  return 1;
                } else {
                  return 1;
                }
              }
            } else {
              if (m->ascii_ratio_rodata <= 0.430371001) {
                if (m->rel32_disp_entropy8 <= 1.020683527) {
                  return 1;
                } else {
                  if (m->align_pad_ratio <= 0.028078000) {
                    return 1;
                  } else {
                    if (m->align_pad_ratio <= 0.033224499) {
                      return 0;
                    } else {
                      return 0;
                    }
                  }
                }
              } else {
                if (m->nop_ratio_text <= 0.002233000) {
                  return 0;
                } else {
                  return 0;
                }
              }
            }
          }
        } else {
          if (m->bss_sz <= 636.000000000) {
            if (m->bss_sz <= 154.000000000) {
              return 1;
            } else {
              return 1;
            }
          } else {
            if (m->jcc32_cnt <= 192.500000000) {
              return 0;
            } else {
              return 1;
            }
          }
        }
      } else {
        if (m->data_ratio <= 0.014155000) {
          if (m->e8_cnt <= 3384.000000000) {
            return 1;
          } else {
            if (m->ro_ratio <= 0.450592995) {
              if (m->rel_branch_ratio <= 0.930093497) {
                return 0;
              } else {
                return 0;
              }
            } else {
              return 1;
            }
          }
        } else {
          if (m->nop_ratio_text <= 0.002992500) {
            if (m->rel32_disp_entropy8 <= 0.780773491) {
              if (m->data_ratio <= 0.027282500) {
                return 0;
              } else {
                if (m->rel_branch_ratio <= 0.890403003) {
                  return 1;
                } else {
                  return 1;
                }
              }
            } else {
              if (m->text_entropy <= 5.940027475) {
                return 1;
              } else {
                if (m->eb_cnt <= 5415.500000000) {
                  if (m->branch_density_per_kb <= 50.761451721) {
                    if (m->jcc32_cnt <= 324.500000000) {
                      return 1;
                    } else {
                      return 1;
                    }
                  } else {
                    if (m->ascii_ratio_rodata <= 0.429992005) {
                      return 1;
                    } else {
                      return 0;
                    }
                  }
                } else {
                  return 1;
                }
              }
            }
          } else {
            if (m->nop_ratio_text <= 0.003093500) {
              if (m->text_entropy <= 6.062113523) {
                return 0;
              } else {
                return 1;
              }
            } else {
              if (m->jcc32_cnt <= 389.500000000) {
                if (m->eb_cnt <= 135.500000000) {
                  if (m->text_ratio <= 0.483891502) {
                    return 1;
                  } else {
                    return 1;
                  }
                } else {
                  if (m->e8_cnt <= 994.500000000) {
                    return 0;
                  } else {
                    if (m->ascii_ratio_rodata <= 0.337595999) {
                      return 1;
                    } else {
                      return 0;
                    }
                  }
                }
              } else {
                if (m->imm64_mov_cnt <= 154.500000000) {
                  if (m->text_entropy <= 6.030388832) {
                    return 1;
                  } else {
                    if (m->imm64_mov_cnt <= 11.500000000) {
                      return 1;
                    } else {
                      return 1;
                    }
                  }
                } else {
                  if (m->data_ratio <= 0.046835499) {
                    return 0;
                  } else {
                    return 1;
                  }
                }
              }
            }
          }
        }
      }
    } else {
      if (m->ro_entropy <= 4.787156582) {
        return 1;
      } else {
        if (m->eb_cnt <= 12015.500000000) {
          return 0;
        } else {
          if (m->file_size <= 17964256.000000000) {
            return 0;
          } else {
            return 0;
          }
        }
      }
    }
  }
}

static inline int zstd_dt_predict_from_pvec(const double *in) {
    zstd_CodecFeat m; memset(&m, 0, sizeof(m));
    m.file_size = in[PP_FEAT_file_size];
    m.text_sz = in[PP_FEAT_text_sz];
    m.ro_sz = in[PP_FEAT_ro_sz];
    m.text_ratio = in[PP_FEAT_text_ratio];
    m.ro_ratio = in[PP_FEAT_ro_ratio];
    m.data_ratio = in[PP_FEAT_data_ratio];
    m.text_entropy = in[PP_FEAT_text_entropy];
    m.ro_entropy = in[PP_FEAT_ro_entropy];
    m.ascii_ratio_rodata = in[PP_FEAT_ascii_ratio_rodata];
    m.e8_cnt = in[PP_FEAT_e8_cnt];
    m.e9_cnt = in[PP_FEAT_e9_cnt];
    m.ff_calljmp_cnt = in[PP_FEAT_ff_calljmp_cnt];
    m.eb_cnt = in[PP_FEAT_eb_cnt];
    m.jcc32_cnt = in[PP_FEAT_jcc32_cnt];
    m.branch_density_per_kb = in[PP_FEAT_branch_density_per_kb];
    m.nop_ratio_text = in[PP_FEAT_nop_ratio_text];
    m.imm64_mov_cnt = in[PP_FEAT_imm64_mov_cnt];
    m.align_pad_ratio = in[PP_FEAT_align_pad_ratio];
    m.rel32_disp_entropy8 = in[PP_FEAT_rel32_disp_entropy8];
    m.bss_sz = in[PP_FEAT_bss_sz];
    m.ret_cnt = in[PP_FEAT_ret_cnt];
    m.rel_branch_ratio = in[PP_FEAT_rel_branch_ratio];
    m.max_rel32_abs = in[PP_FEAT_max_rel32_abs];
    return zstd_dt_core(&m);
}

#ifdef __cplusplus
}
#endif
