// Auto-generated by tools/ml/train_codec_predictor.py
#pragma once
// Returns 0 for BCJ, 1 for KANZIEXE
#ifdef __cplusplus
extern "C" {
#endif
#include "exe_predict_feature_index.h"

// Minimal feature struct (only used fields)
typedef struct {
    double eb_cnt;
    double jcc32_cnt;
    double rel_branch_ratio;
} zx0_CodecFeat;

static inline int zx0_dt_core(const zx0_CodecFeat *m) {
  if (m->jcc32_cnt <= 1752.500000000) {
    if (m->rel_branch_ratio <= 0.950331002) {
      if (m->jcc32_cnt <= 915.500000000) {
        return 0;
      } else {
        if (m->eb_cnt <= 243.500000000) {
          return 0;
        } else {
          return 0;
        }
      }
    } else {
      return 0;
    }
  } else {
    return 0;
  }
}

static inline int zx0_dt_predict_from_pvec(const double *in) {
    zx0_CodecFeat m; memset(&m, 0, sizeof(m));
    m.eb_cnt = in[PP_FEAT_eb_cnt];
    m.jcc32_cnt = in[PP_FEAT_jcc32_cnt];
    m.rel_branch_ratio = in[PP_FEAT_rel_branch_ratio];
    return zx0_dt_core(&m);
}

#ifdef __cplusplus
}
#endif
