// Auto-generated by tools/ml/train_codec_predictor.py
#pragma once
// Returns 0 for BCJ, 1 for KANZIEXE
#ifdef __cplusplus
extern "C" {
#endif
#include "exe_predict_feature_index.h"

// Minimal feature struct (only used fields)
typedef struct {
    double file_size;
    double text_sz;
    double data_sz;
    double text_ratio;
    double data_entropy;
    double e9_cnt;
    double eb_cnt;
    double jcc32_cnt;
    double branch_density_per_kb;
    double ro_ptr_like_cnt;
    double ret_cnt;
} CodecFeat;

static inline int zx7b_dt_core(const CodecFeat *m) {
  if (m->jcc32_cnt <= 1225.000000000) {
    if (m->file_size <= 382556.000000000) {
      if (m->jcc32_cnt <= 889.000000000) {
        if (m->data_sz <= 41912.000000000) {
          return 0;
        } else {
          return 0;
        }
      } else {
        if (m->eb_cnt <= 211.500000000) {
          return 0;
        } else {
          if (m->text_sz <= 114477.000000000) {
            return 0;
          } else {
            return 0;
          }
        }
      }
    } else {
      return 1;
    }
  } else {
    if (m->jcc32_cnt <= 1749.000000000) {
      if (m->text_ratio <= 0.578203022) {
        if (m->data_entropy <= 2.041958451) {
          return 1;
        } else {
          return 1;
        }
      } else {
        if (m->ro_ptr_like_cnt <= 639.500000000) {
          return 1;
        } else {
          if (m->branch_density_per_kb <= 40.425333023) {
            return 0;
          } else {
            return 0;
          }
        }
      }
    } else {
      if (m->data_sz <= 4120.000000000) {
        return 1;
      } else {
        if (m->branch_density_per_kb <= 24.031989098) {
          return 1;
        } else {
          if (m->e9_cnt <= 2546.000000000) {
            if (m->ret_cnt <= 1643.000000000) {
              return 1;
            } else {
              return 1;
            }
          } else {
            return 1;
          }
        }
      }
    }
  }
}

static inline int zx7b_dt_predict_from_pvec(const double *in) {
    CodecFeat m; memset(&m, 0, sizeof(m));
    m.file_size = in[PP_FEAT_file_size];
    m.text_sz = in[PP_FEAT_text_sz];
    m.data_sz = in[PP_FEAT_data_sz];
    m.text_ratio = in[PP_FEAT_text_ratio];
    m.data_entropy = in[PP_FEAT_data_entropy];
    m.e9_cnt = in[PP_FEAT_e9_cnt];
    m.eb_cnt = in[PP_FEAT_eb_cnt];
    m.jcc32_cnt = in[PP_FEAT_jcc32_cnt];
    m.branch_density_per_kb = in[PP_FEAT_branch_density_per_kb];
    m.ro_ptr_like_cnt = in[PP_FEAT_ro_ptr_like_cnt];
    m.ret_cnt = in[PP_FEAT_ret_cnt];
    return zx7b_dt_core(&m);
}

#ifdef __cplusplus
}
#endif
